"""onboarding profile workplace places catalog

Revision ID: 5041b785e4ed
Revises: 0001
Create Date: 2026-09-22 14:58:48.760034

"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'label', name='uq_catalog_kind_label')
    )
    op.create_index(op.f('ix_catalog_items_kind'), 'catalog_items', ['kind'], unique=False)
    op.create_table('onboarding_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('saved_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('address_line', sa.String(length=400), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_place_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_places_user_id'), 'saved_places', ['user_id'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('degrees', sa.JSON(), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=False),
    sa.Column('nursing_qualifications', sa.JSON(), nullable=False),
    sa.Column('medical_council_reg_no', sa.String(length=64), nullable=True),
    sa.Column('nursing_council_reg_no', sa.String(length=64), nullable=True),
    sa.Column('certification_level', sa.String(length=64), nullable=True),
    sa.Column('paramedic_licence_no', sa.String(length=64), nullable=True),
    sa.Column('role_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workplace_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=True),
    sa.Column('organisation_name', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
    _seed_catalog()


def _seed_catalog() -> None:
    """Fill catalog_items from app/catalog/data.py.

    The app reads these lists, so an empty table would leave every picker
    blank. Seeding here means a fresh database is usable immediately.
    """
    from app.catalog.data import CATALOGS

    rows = [
        {"id": uuid.uuid4(), "kind": kind.value, "label": label,
         "sort_order": order, "is_active": True}
        for kind, labels in CATALOGS.items()
        for order, label in enumerate(labels)
    ]
    op.bulk_insert(
        sa.table(
            "catalog_items",
            sa.column("id", sa.Uuid()),
            sa.column("kind", sa.String()),
            sa.column("label", sa.String()),
            sa.column("sort_order", sa.Integer()),
            sa.column("is_active", sa.Boolean()),
        ),
        rows,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workplace_memberships')
    op.drop_table('worker_profiles')
    op.drop_index(op.f('ix_saved_places_user_id'), table_name='saved_places')
    op.drop_table('saved_places')
    op.drop_table('onboarding_states')
    op.drop_index(op.f('ix_catalog_items_kind'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
