"""Place visibility, and About and tags on the profile.

Existing places become private, existing profiles get no tags.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 17:09:30.071940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_places', sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False))
    op.add_column('worker_profiles', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('worker_profiles', sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'tags')
    op.drop_column('worker_profiles', 'about')
    op.drop_column('saved_places', 'visibility')
    # ### end Alembic commands ###
